### 🔐 Connexion étudiant (OK)
POST http://localhost:8080/api/utilisateurs/login
Content-Type: application/json
Accept: application/json

{
  "email": "amin@gmail.com",
  "motDePasse": "123456"
}


### 🔐 Connexion professeur (OK)
POST http://localhost:8080/api/utilisateurs/login
Content-Type: application/json
Accept: application/json

{
  "email": "prof@example.com",
  "motDePasse": "123456"
}


### ❌ Connexion incorrecte (email ou mot de passe faux)
POST http://localhost:8080/api/utilisateurs/login
Content-Type: application/json
Accept: application/json

{
  "email": "wrong@example.com",
  "motDePasse": "badpass"
}
