### 🔐 Connexion étudiant (OK)
POST http://localhost:8080/api/utilisateurs/login
Content-Type: application/json
Accept: application/json

{
  "email": "amin@gmail.com",
  "motDePasse": "123456"
}


### 🔐 Connexion professeur (OK)
POST http://localhost:8080/api/utilisateurs/login
Content-Type: application/json
Accept: application/json

{
  "email": "prof@example.com",
  "motDePasse": "123456"
}


### ❌ Connexion incorrecte (email ou mot de passe faux)
POST http://localhost:8080/api/utilisateurs/login
Content-Type: application/json
Accept: application/json

{
  "email": "wrong@example.com",
  "motDePasse": "badpass"
}



### 
POST http://localhost:8080/api/classes/10/add-professeur/1
Content-Type: application/json



### Add a question to exam with ID 1
GET http://localhost:8080/api/examens/5/details
Content-Type: application/json



############################################
# ADD a question to exam (one by one)
############################################
POST http://localhost:8080/api/examens/5/questions
Content-Type: application/json

{
  "type": "CHOICE",
  "contenu": "What is Java Spring Boot?",
  "options": "Framework, Database, IDE",
  "reponseCorrecte": "Framework"
}


############################################
POST http://localhost:8080/api/examens/5/questions
Content-Type: application/json

{
  "type": "CHOICE",
  "contenu": "What is the capital of France?",
  "options": ["Paris", "Lyon", "Marseille"],
  "reponseCorrecte": "Paris"
}

############################################
POST http://localhost:8080/api/examens/5/questions
Content-Type: application/json

{
  "type": "MULTIPLE",
  "titre": "What is 2+2?",
  "choix": "1,2,3,4",
  "correct": "4"
}