### 🔐 Connexion étudiant (OK)
POST http://localhost:8080/api/utilisateurs/login
Content-Type: application/json
Accept: application/json

{
  "email": "amin@gmail.com",
  "motDePasse": "123456"
}


### 🔐 Connexion professeur (OK)
POST http://localhost:8080/api/utilisateurs/login
Content-Type: application/json
Accept: application/json

{
  "email": "prof@example.com",
  "motDePasse": "123456"
}


### ❌ Connexion incorrecte (email ou mot de passe faux)
POST http://localhost:8080/api/utilisateurs/login
Content-Type: application/json
Accept: application/json

{
  "email": "wrong@example.com",
  "motDePasse": "badpass"
}



### 
POST http://localhost:8080/api/classes/10/add-professeur/1
Content-Type: application/json



### Add a question to exam with ID 1
POST http://localhost:8080/api/examens/2/questions
Content-Type: application/json

{
  "type": "QCM",
  "contenu": "Quelle est la couleur du ciel?",
  "options": "Bleu,Vert,Jaune,Rouge",
  "reponseCorrecte": "Bleu"
}
